Feature/release status
ONSdigital/dp-frontend-articles-controller pull request #17
Opened 2022-06-27 14:35 UTC by gilesburdett

### What

The article's release status (latest, superseded, or outdated) is indicated alongside a relevant link to other versions from the perspective of the version being displayed.

<img width="720" alt="Screenshot 2022-06-27 at 15 29 54" src="https://user-images.githubusercontent.com/912770/175965898-032ba56f-9741-4199-9cd2-92d5bef99238.png">
<img width="734" alt="Screenshot 2022-06-27 at 15 29 36" src="https://user-images.githubusercontent.com/912770/175965789-3c807ae0-ee8d-4e18-9998-d7a11b33c883.png">
<img width="746" alt="Screenshot 2022-06-27 at 15 29 05" src="https://user-images.githubusercontent.com/912770/175965796-66fde027-68db-4b59-8271-adb541af9b70.png">

### How to review

- In a separate shell, run the dp-design-system with `make debug`
- Run this frontend with `make debug`
- View different versions of article to verify that the appropriate version status and link are shown

### Who can review

Front end / design system developers

2022-06-28 13:35 UTC, mr-nick17 requested changes

2022-06-28 13:35 UTC, mr-nick17 commented on assets/locales/service.en.toml
> +one = "LATEST"
Using uppercase [might be difficult](https://a11y-101.com/design/capitalisation) for users with accessibility needs. Could you keep the text as lower/title case and then use css (`ons-u-tt-u`) to transform?

2022-06-28 13:48 UTC, gilesburdett commented on assets/locales/service.en.toml
> +one = "LATEST"
Cracking idea (and that's another utility class worth knowing about!)

2022-06-28 14:02 UTC, mr-nick17 approved these changes, later dismissed

2022-07-05 09:32 UTC, mr-nick17 approved these changes

2022-07-05 09:33 UTC, merged